name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  coverage:

    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - run: npm install -g coveralls
    - run: npm test -- --coverage
    - run: cat coverage/lcov.info | coveralls
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
