name: Node.js CI

on:
  - push
  - pull_request

jobs:
  build-and-coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Print Current Directory and List Files
        run: |
          pwd
          ls

      - name: Install Dependencies and Build
        run: |
          npm ci
          npm run build --if-present

      - name: Run Tests
        run: npm test

      - name: Run Tests with Coverage and Publish to Coveralls
        env:
          CI: true
        run: |
          npm test -- --coverage
          npm install -g coveralls
          cat coverage/lcov.info | coveralls
        
